app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'auth'), function()
{
	\Route::get('elfinder', 'Barryvdh\Elfinder\ElfinderController@showIndex');
	\Route::any('elfinder/connector', 'Barryvdh\Elfinder\ElfinderController@showConnector');
});

Route::group(array('prefix' => 'dashboard'), function()
{
	/**
	 *
	 *
	 */
	Route::get('sandbox/{slug}', 'HomeController@getSandbox');
	
	/**
	 * @link dashboard/account
	 * Accounts management routes
	 */
	Route::resource('account', 'UserController');

	/**
	 * @link dashboard/page/*
	 * Page routes
	 */
	Route::resource('page', 'PageController');

	/**
	 * @link dashboard/file/
	 * File management API route
	 */
	Route::controller('file', 'FileController');

	/**
	 * @link dashboard/auth/*
	 * Authentication routes
	 */
	Route::controller('auth', 'AuthController');

	/**
	 * @link system
	 * System settings routes
	 */
	Route::controller('settings', 'SettingController');

	/**
	 * @link dashboard
	 * Dashboard routes
	 */
	Route::controller('/', 'DashboardController');
});

/**
 * @link /mail/us
 * Module (mail)
 */ 
Route::post('mail/us', 'ModuleController@postSendMail');

/**
 * @link /*(slug)
 * Live pages
 */
Route::get('/', 'HomeController@getIndex');
Route::get('{slug}', 'HomeController@getPage');

app/controllers/Dashboard/AuthController.php
<?php

/**
 * Controller which handles the authentication
 * of users and administrators
 *
 */
class AuthController extends BaseController {

	/**
	 *
	 *
	 */
	public function __construct()
	{
		$this->beforeFilter('csrf', array('only' => array('postLogin')));
		$this->beforeFilter('guest', array('except' => array('getLogout')));
		$this->beforeFilter('auth', array('only' => array('getLogout')));
	}

	/**
	 *
	 *
	 */
	public function getIndex()
	{
		return View::make('dashboard/auth.blank');
	}

	/**
	 * Login the authenticated user
	 *
	 * @return 	Response
	 */
	public function postLogin()
	{
		try {
			// Set login credentials
			$credentials = array(
				'email'		=>	Input::get('email'),
				'password'	=>	Input::get('password')
			);

			// Try to authenticate the user
			$user = Sentry::authenticate($credentials, false);
		} catch (Cartalyst\Sentry\Users\LoginRequiredException $e) {
			$message = 'Pålogging feltet er påkrevd.';
		} catch (Cartalyst\Sentry\Users\PasswordRequiredException $e) {
			$message = 'Passord feltet er påkrevd.';
		} catch (Cartalyst\Sentry\Users\WrongPasswordException $e) {
			$message = 'Feil passord, prøv igjen.';
		} catch (Cartalyst\Sentry\Users\UserNotFoundException $e) {
			$message = 'Bruker ble ikke funnet.';
		} catch (Cartalyst\Sentry\Users\UserNotActivatedException $e) {
			$message = 'Brukeren er ikke aktivert.';
		}

		if(empty($message)) {
			Session::flash('success', 'Du har logget inn');
			return Redirect::to('dashboard');
		}

		Session::flash('error', $message);
		return Redirect::to('dashboard/auth');
	}

	/**
	 * Logout the authenticated user
	 *
	 * @return 	Response
	 */
	public function getLogout()
	{
		Sentry::logout();
		Session::flash('success', 'Du har klart logget ut!');
		return Redirect::to('dashboard/auth');
	}
}

app/controllers/Dashboard/DashboardController.php
<?php

class DashboardController extends BaseController {

	/**
	 *
	 *
	 */
	public function __construct()
	{		
		$this->beforeFilter('auth', array('only' => array('getIndex')));
	}

	/**
	 * Display the dashboard
	 *
	 * @return 	Response
	 */
	public function getIndex()
	{
		return View::make('dashboard.index');
	}
}

app/controllers/Dashboard/FileController.php
<?php

class FileController extends BaseController {

	/**
	 *
	 *
	 */
	public function __construct()
	{
		$this->beforeFilter('auth', array('only' => array('getIndex')));
	}

	/**
	 *
	 *
	 */
	public function getIndex()
	{
		return View::make('dashboard/file.index');
	}
}

app/controllers/Dashboard/ModuleController.php
<?php

class ModuleController extends BaseController {

	/**
	 * Process the mailing
	 *
	 *
	 */
	public function postSendMail()
	{
		$errors = [];

		Validator::extend('alpha_space', function($attr, $value) {
    		return preg_match('/^([a-z\x20])+$/i', $value);
		});
		$rules = array(
			'email'			=>	'required|email',
			'subject'		=>	'required|between:10,64',
			'full_name'		=>	'required|alpha_space',
			'message'		=>	'required|min:25'
		);

		$validation = Validator::make(Input::all(), $rules);

		if($validation->passes()) {
			$msg = Input::get('message');

			$data = [
				'msg'	=>	$msg
			];

			$to = Setting::email();
			$subject = Input::get('subject');
			$from = Input::get('email');
			$name = Input::get('full_name');

			Mail::send('template.email', $data, function($message) use($to, $from, $subject, $name)
			{
				$message->from($from, $name)
				->to($to)
				->subject($subject);
			});

			Session::flash('success', 'Mail has been sent');
			return Response::json(array(
				'status'	=>	true
			));
		}

		$messages = $validation->messages();
		$errors['full_name']	= $messages->first('full_name');
		$errors['email']		= $messages->first('email');
		$errors['message']		= $messages->first('message');
		$errors['subject']		= $messages->first('subject');

		return Response::json(array(
			'status'	=>	false,
			'error'		=>	'An error has occured',
			'errors'	=>	$errors
		));

	}
}

app/controllers/Dashboard/PageController.php
<?php

class PageController extends BaseController {

	/**
	 *
	 *
	 *
	 */
	public function __construct()
	{
		$this->beforeFilter('auth', array('only' => array(
			'index', 'create', 'store', 'show',
			'edit', 'update', 'delete'
		)));
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$pages = Page::all();
		return View::make('dashboard/page.index')
			->with('pages', $pages);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('dashboard/page.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$errors = [];
		// $parent = Page::setParent(Input::get('parent'));
		$order = Page::getLastOrder()->order + 1;
		$inNavigation = (Input::get('inNavigation') == "true")
			? true
			: false;

		$live = (Input::get('live') == "true")
			? true
			: false;

		$title = Input::get('title');
		$slug = (!Input::has('slug'))
			? Page::slugify($title)
			: Input::get('slug');
		
		$slug_exists = Page::where('slug', '=', $slug)
			->get();

		if($slug == 'dashboard') {
			$errors['slug'] = 'Permalink brukte søkeordet: [dashbord]';
		} elseif(!is_null($slug_exists) &&
			!empty($slug_exists) &&
			count($slug_exists) >= 1) {
			$errors['slug'] = 'Innsatt slug finnes allerede';
		}

		$parent = 0;
		$body = Input::get('body');

		$metaDescription = Input::get('metaDescription');

		$page = new Page(array(
			'parent_id'			=> 	$parent,
			'title'				=>	$title,
			'body'				=>	$body,
			'slug'				=>	$slug,
			'live'				=>	$live,
			'inNavigation'		=>	$inNavigation,
			'isHome'			=>	false,
			'order'				=>	$order,
			'metaDescription'	=>	$metaDescription
		));

		if(count($errors) === 0) {
			if($page->save()) {
				$success = $page->title .
					' har blitt opprettet!';
				Session::flash('success', $success);
				return Response::json(array(
					'status'	=>	true
				));
			}
		}

		$error = 'Det har oppstått en feil';
		return Response::json(array(
			'status'	=>	false,
			'error'		=>	$error,
			'errors'	=>	$errors
		));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$page = Page::find($id);
		if($page->live)
			return Redirect::to('/' . $page->slug);

		return Redirect::to('/');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$page = Page::find($id);
		
		return View::make('dashboard/page.edit')
			->with('page', $page);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$errors = [];
		$page = Page::find($id);
		$navigation = (Input::get('inNavigation') == "true")
			? true
			: false;

		$live = (Input::get('live') == "true")
			? true
			: false;


		// Process appropriate slug
		$title = Input::get('title');
		$slug = (!Input::has('slug'))
			? Page::slugify($title)
			: Input::get('slug');

		if($slug == 'dashboard') {
			$errors['slug'] = 'Permalink brukte søkeordet: [dashbord]';
		} elseif($slug !== $page->slug) {
			$slug_exists = Page::where('slug', $slug)
				->get();
				
			if(!is_null($slug_exists) &&
				!empty($slug_exists) &&
				count($slug_exists) >= 1) {
				$errors['slug'] = 'Innsatt slug finnes allerede';
			}
		}

		// Process homepage
		$home = (Input::get('isHome') == "true")
			? true
			: false;
		$sg = Input::get('isHome');
		// return Response::json(array($sg, $home));
		if(!$page->isHome && $home) {
			Page::setHome($page);
		}

		// Process page order
		$order = Input::get('order');
		if($page->order !== $order) {
			$page->order = Page::setOrder($order, $page);
		}

		$body = Input::get('body');

		$metaDescription = Input::get('metaDescription');

		// [] Parent
		$page->title				=	$title;
		$page->body					=	$body;
		$page->slug					=	$slug;
		$page->live					=	$live;
		$page->inNavigation			=	$navigation;
		$page->order				=	$order;
		$page->metaDescription		=	$metaDescription;
		if(count($errors) == 0) {
			if($page->save()) {
				$success = $page->title .
					' har blitt vellykket oppdatert!';
				Session::flash('success', $success);
				return Response::json(array(
					'status'	=>	true
				));
			}
		}

		$error = 'Det har oppstått en feil';
		return Response::json(array(
			'status'	=>	false,
			'error'		=>	$error,
			'errors'	=>	$errors
		));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$page = Page::find($id);

		$isHome = ($page->isHome)
			? true
			: false;

		$status = ($page->delete())
			? true
			: false;

		Page::decrementOrderOnDelete($page);
		if($isHome) Page::selectDefaultHome();

		if($status) {		
			$success = $page->title . ' page has been deleted';
			Session::flash('success', $success);
		} else {
			$error = 'An error has occured while deleting ' . $page->title;
			Session::flash('error', $error);
		}

		return Response::json(array(
				'status'	=>	$status
		));
	}

}

app/controllers/Dashboard/SettingController.php
<?php

class SettingController extends BaseController {

	/**
	 *
	 *
	 */
	public function __construct()
	{		
		$this->beforeFilter('auth', array('only' => array('getIndex', 'putIndex')));
	}

	/**
	 * Display system settings
	 *
	 * @return 	Response
	 */
	public function getIndex()
	{
		return View::make('dashboard/settings.index');
	}

	/**
	 * Update system settings
	 *
	 * @return 	Response
	 */
	public function putIndex()
	{
		$title = Setting::getRequested('title');
		$slogan = Setting::getRequested('slogan');
		$email = Setting::getRequested('email');
		$footer = Setting::getRequested('footer');
		$liveSite = Setting::getRequested('liveSite');
		$frontDescription = Setting::getRequested('frontDescription');

		$isLive = (Input::has('liveSite'))
			? '1'
			: '0';

		$title->value = Input::get('title');
		$slogan->value = Input::get('slogan');
		$email->value = Input::get('email');
		$footer->value = Input::get('footer');
		$liveSite->value = $isLive;
		$frontDescription->value = Input::get('frontDescription');
		if($title->save() &&
			$slogan->save() &&
			$email->save() &&
			$footer->save() &&
			$liveSite->save() &&
			$frontDescription->save()) {
			Session::flash('success', 'Konfigurasjoner har blitt oppdatert');
			return Redirect::to('dashboard/settings');
		}
	}

}

app/controllers/Dashboard/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$users = Sentry::findAllUsers();

		return View::make('dashboard/user.index')
			->with('users', $users);;
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{	

		return View::make('dashboard/user.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validation = User::validate(Input::all());
		if($validation->passes()) {

			$activated = (Input::get('activated') == "true")
				? true
				: false;

			$user = array(
				'email'			=>	Input::get('email'),
				'password'		=>	Input::get('password'),
				'activated'		=>	$activated,
				'first_name'	=>	Input::get('first_name'),
				'last_name'		=>	Input::get('last_name')
			);

			if(Sentry::register($user)) {
				Session::flash('success', 'En ny bruker er lagt til!');
				return Response::json(array(
					'status'	=>	true
				));
			}
		}
		
		// return Response::json($validation->messages());
		$error = 'Det har oppstått en feil under oppretting av brukeren';
		return Response::json(array(
			'status'	=>	false,
			'error'		=>	$error,
			'errors'	=>	$validation->messages()->all()
		));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$user = Sentry::findUserById($id);

		return View::make('dashboard/user.edit')
			->with('user', $user);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$errors = [];
		$user = Sentry::findUserById($id);
		$validation = User::validate(Input::all(), 2);

		$activated = (Input::get('activated') == "true")
			? true
			: false;
		if($validation->passes()) {
			// $user->email		=	Input::get('email');
			$user->password		=	Input::get('password');
			$user->activated	=	$activated;
			$user->first_name	=	Input::get('first_name');
			$user->last_name	=	Input::get('last_name');

			if($user->save()) {
				Session::flash('success', 'En ny bruker er lagt!');
				return Response::json(array(
					'status'	=>	true
				));
			}
		}

		$error = 'Det har oppstått en feil under oppretting av brukeren';
		return Response::json(array(
			'status'	=>	false,
			'error'		=>	$error,
			'errors'	=>	$errors
		));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$user = Sentry::findUserById($id);
		$status = ($user->delete())
			? true
			: false;		

		if($status) {
			Session::flash('success', 'Brukeren er blitt slettet');
		} else {
			Session::flash('error', 'Det har oppstått en feil under sletting av bruker');
		}
		return Response::json(array(
			'status'	=>	$status
		));
	}

}

app/views/dashboard/page/create.blade.php
@extends('template.dashboard')

@section('title') - Opprett ny side @stop

@section('content')
<div class="page-header">
	<h1> Opprett ny side </h1>
</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								{{ Form::open(array('id' => 'form-create')) }}
									{{ Form::token() }}
									<div class="row">
										<div class="col-xs-6">
											<div id="title" class="form-group">
												<label>
													Tittel
													(<b id="meta-title-length" class="red">0</b>/70)
												</label>
												<input name="title" type="text" class="form-control">
												<p class="help-block">&nbsp;</p>
											</div>
										</div>

										<div class="col-xs-6">
											<div id="slug" class="form-group">
												<label> Custom Slug </label>
												<input name="slug" type="text" class="form-control">
												<p class="help-block"> I nettadressen vil det komme adressen og så vil det være en «/» som spesifiserer hvilken underside du er på. (Eksempel: <em> www.marikova.no/kontakt </em>) </p>
											</div>
										</div>
									</div>

									<h4 class="header green clearfix">
										Innhold
										<span class="block pull-right">
											<small class="grey middle">Velg stil: &nbsp;</small>

											<span class="btn-toolbar inline middle no-margin">
												<span data-toggle="buttons" class="btn-group no-margin">
													<label class="btn btn-sm btn-yellow">
														1
														<input type="radio" value="1" />
													</label>

													<label class="btn btn-sm btn-yellow active">
														2
														<input type="radio" value="2" />
													</label>

													<label class="btn btn-sm btn-yellow">
														3
														<input type="radio" value="3" />
													</label>
												</span>
											</span>
										</span>
									</h4>

									<div class="wysiwyg-editor" id="editor1"></div>

									<script type="text/javascript">
										var $path_assets = "assets";//this will be used in loading jQuery UI if needed!
									</script>

									<div class="space-6"></div>
									<div class="row">
										<div class="col-xs-4">
												<label class="inline">
													<small> Gjør siden live: </small>
													<input name="live" class="ace ace-switch ace-switch-5" type="checkbox"/>
													<span class="lbl"></span>
												</label>
										</div>

										<div class="col-xs-4">
											<label class="inline">
												<small> Vis i navigeringen: </small>
												<input name="inNavigation" type="checkbox" class="ace ace-switch ace-switch-5" />
												<span class="lbl"></span>
											</label>
										</div>
									</div>

									<div class="space-6"></div>
									<div class="row">
										<div class="col-xs-6">
											<div class="form-group">
												<label>
													Meta Beskrivelse
													(<b id="meta-description-length" class="red">0</b>/152)
												</label>
												<textarea name="metaDescription" class="form-control"></textarea>
												<p class="help-block"> Meta beskrivelsen er en beskrivelse av siden, som vil bli synlig gjennom søkemotorer. </p>
											</div>
										</div>

										<div class="col-xs-6">
											<div class="form-group">
												<label> SEO Forhåndsvisning: </label>
												<blockquote>
													<p id="meta-title" style="margin-bottom: 0">
														<a href="#" style="color: blue; text-decoration: underline; font-family: Arial">
															{{ Setting::title() }}&nbsp;-&nbsp;
														</a>
													</p>

													<p id="meta-slug" style="color: green; font-size:14px; font-family: Arial; margin-bottom: 0">
														{{ url() }}
													</p>

													<p id="meta-description" style="font-family: Arial; font-size: 13px"></p>
												</blockquote>
											</div>
										</div>
									</div>

									<br />
									<div class="form-group">									
										<button id="form-submit" type="submit" class="btn btn-success">
											<i class="icon-ok"></i>
											Opprett side
										</button>
									</div>
								{{ Form::close() }}
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
@stop

@section('page_scripts')
	<!-- page specific plugin scripts -->

	{{ HTML::script('assets/js/jquery-ui-1.10.3.custom.min.js') }}
	{{ HTML::script('assets/js/jquery.ui.touch-punch.min.js') }}
	{{ HTML::script('assets/js/markdown/markdown.min.js') }}
	{{ HTML::script('assets/js/markdown/bootstrap-markdown.min.js') }}
	{{ HTML::script('assets/js/jquery.hotkeys.min.js') }}
	{{ HTML::script('assets/js/bootstrap-wysiwyg.min.js') }}
	{{ HTML::script('assets/js/bootbox.min.js') }}
@stop

@section('inline_scripts')
	<script type="text/javascript">
				jQuery(function($){
		
		function showErrorAlert (reason, detail) {
			var msg='';
			if (reason==='unsupported-file-type') { msg = "Unsupported format " +detail; }
			else {
				console.log("error uploading file", reason, detail);
			}
			$('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>'+ 
			 '<strong>File upload error</strong> '+msg+' </div>').prependTo('#alerts');
		}

		//$('#editor1').ace_wysiwyg();//this will create the default editor will all buttons

		//but we want to change a few buttons colors for the third style
		$('#editor1').ace_wysiwyg({
			toolbar:
			[
				'font',
				null,
				'fontSize',
				null,
				{name:'bold', className:'btn-info'},
				{name:'italic', className:'btn-info'},
				{name:'strikethrough', className:'btn-info'},
				{name:'underline', className:'btn-info'},
				null,
				{name:'insertunorderedlist', className:'btn-success'},
				{name:'insertorderedlist', className:'btn-success'},
				{name:'outdent', className:'btn-purple'},
				{name:'indent', className:'btn-purple'},
				null,
				{name:'justifyleft', className:'btn-primary'},
				{name:'justifycenter', className:'btn-primary'},
				{name:'justifyright', className:'btn-primary'},
				{name:'justifyfull', className:'btn-inverse'},
				null,
				{name:'createLink', className:'btn-pink'},
				{name:'unlink', className:'btn-pink'},
				null,
				{name:'insertImage', className:'btn-success'},
				null,
				'foreColor',
				null,
				{name:'undo', className:'btn-grey'},
				{name:'redo', className:'btn-grey'}
			],
			'wysiwyg': {
				fileUploadError: showErrorAlert
			}
		}).prev().addClass('wysiwyg-style2');

		

		$('#editor2').css({'height':'200px'}).ace_wysiwyg({
			toolbar_place: function(toolbar) {
				return $(this).closest('.widget-box').find('.widget-header').prepend(toolbar).children(0).addClass('inline');
			},
			toolbar:
			[
				'bold',
				{name:'italic' , title:'Change Title!', icon: 'icon-leaf'},
				'strikethrough',
				null,
				'insertunorderedlist',
				'insertorderedlist',
				null,
				'justifyleft',
				'justifycenter',
				'justifyright'
			],
			speech_button:false
		});


		$('[data-toggle="buttons"] .btn').on('click', function(e){
			var target = $(this).find('input[type=radio]');
			var which = parseInt(target.val());
			var toolbar = $('#editor1').prev().get(0);
			if(which == 1 || which == 2 || which == 3) {
				toolbar.className = toolbar.className.replace(/wysiwyg\-style(1|2)/g , '');
				if(which == 1) $(toolbar).addClass('wysiwyg-style1');
				else if(which == 2) $(toolbar).addClass('wysiwyg-style2');
			}
		});


		

		//Add Image Resize Functionality to Chrome and Safari
		//webkit browsers don't have image resize functionality when content is editable
		//so let's add something using jQuery UI resizable
		//another option would be opening a dialog for user to enter dimensions.
		if ( typeof jQuery.ui !== 'undefined' && /applewebkit/.test(navigator.userAgent.toLowerCase()) ) {
			
			var lastResizableImg = null;
			function destroyResizable() {
				if(lastResizableImg == null) return;
				lastResizableImg.resizable( "destroy" );
				lastResizableImg.removeData('resizable');
				lastResizableImg = null;
			}

			var enableImageResize = function() {
				$('.wysiwyg-editor')
				.on('mousedown', function(e) {
					var target = $(e.target);
					if( e.target instanceof HTMLImageElement ) {
						if( !target.data('resizable') ) {
							target.resizable({
								aspectRatio: e.target.width / e.target.height,
							});
							target.data('resizable', true);
							
							if( lastResizableImg != null ) {//disable previous resizable image
								lastResizableImg.resizable( "destroy" );
								lastResizableImg.removeData('resizable');
							}
							lastResizableImg = target;
						}
					}
				})
				.on('click', function(e) {
					if( lastResizableImg != null && !(e.target instanceof HTMLImageElement) ) {
						destroyResizable();
					}
				})
				.on('keydown', function() {
					destroyResizable();
				});
		    }
			
			enableImageResize();

			/**
			//or we can load the jQuery UI dynamically only if needed
			if (typeof jQuery.ui !== 'undefined') enableImageResize();
			else {//load jQuery UI if not loaded
				$.getScript($path_assets+"/js/jquery-ui-1.10.3.custom.min.js", function(data, textStatus, jqxhr) {
					if('ontouchend' in document) {//also load touch-punch for touch devices
						$.getScript($path_assets+"/js/jquery.ui.touch-punch.min.js", function(data, textStatus, jqxhr) {
							enableImageResize();
						});
					} else	enableImageResize();
				});
			}
			*/
		}
	});
			</script>
@stop

@section('scripts')
	<script>
		function createError(message) {
			return '<div class="alert alert-danger error">' +
				message +
				'</div>';
		}

		var baseTitle = '{{ Setting::title() }} - ';
		var baseURL = '{{ url() }}/';

		var title = $('[name=title]');
		var slug = $('[name=slug]');
		var metaDesc = $('[name=metaDescription]');

		title.on('click', function() {
			var self = $(this);
			self.keyup(function() {
				var length = self.val().length;
				var limit = 70;
				$('p#meta-title a').text(baseTitle + self.val());
				$('b#meta-title-length').text(length);
				if(length > limit) {
					self.val(self.val().toString().substring(0, limit))
				}
			})
		});

		slug.on('click', function() {
			var self = $(this);
			self.keyup(function() {
				$('p#meta-slug').text(baseURL + self.val());
			})
		});

		metaDesc.on('click', function() {
			var self = $(this);
			self.keyup(function(e) {
				var length = self.val().length;
				var limit = 152;
				$('p#meta-description').text(self.val());
				$('b#meta-description-length').text(length);
				if(length > limit) {
					self.val(self.val().toString().substring(0, limit))
				}
			});
		});


		$("#form-submit").on('click', function(e) {
			e.preventDefault();

			// If there are errors present in the screen
			var $e;
			if(($e = $('.error')).length >= 1)
				$e.remove();

			var live = ($('[name=live]').is(':checked'))
				? true
				: false;

			var inNavigation = ($('[name=inNavigation]').is(':checked'))
				? true
				: false;

			$.ajax({
				url: '{{ URL::route('dashboard.page.store') }}' + '?body=' + $('#editor1').html(),
				type: 'POST',
				data: {
					title: title.val(),
					slug: slug.val(),
					live: live,
					inNavigation: inNavigation,
					metaDescription : metaDesc.val()
				},
				dataType: 'json',
				success: function(data) {
					// Remove the error
					var $e;
					if(($e = $('.error')).length >= 1)
						$e.remove();

					if(!data.status) {
						var error;
						$('#form-create').prepend(createError(data.error));

						if(data.errors.slug !== undefined) {
							console.log('oyyy');
							error = createError(data.errors.slug);
							$('#slug').append(error);
							error = undefined;
						}
					} else {
						window.location = '{{ URL::route('dashboard.page.index') }}';
					}
				}
			});
		});
	</script>
@stop